package scenario;

import java.util.ArrayList;
import java.util.HashMap;

/**
 *
 * @author Nicolas Brax
 */
public class Scenario {
  
  /****************************************************************************/
  /** Private Attributes                                                     **/
  /****************************************************************************/
  
  /**
   * The title of the scenario as defined by the user.
   */
  private String title;
  
  /**
   * A map of all the element constituting the current scenario. Each element is
   * referenced by a unique identificator within the scenario. This id can be
   * generated by the scenario.
   */
  private HashMap<String,ScenarioElement> scenario;
  
  /**
   * A counter of element used to generate a unique id for the element of 
   * the scenario.
   */
  private static long idCounter = 0;
  
  
  /****************************************************************************/
  /** Constructor Methods                                                    **/
  /****************************************************************************/
  
  /**
   * Default Consructor.
   * Set the title to an empty character string and initialize the element map.
   */
  public Scenario(){
    this.title = "";
    this.scenario = new HashMap<>();
  }
  
  
  /****************************************************************************/
  /** Getter and Setter Methods                                              **/
  /****************************************************************************/
  
  /**
   * 
   * @param elementId
   * @return 
   */
  public ScenarioElement getElement(String elementId){
    return this.scenario.get(elementId);
  }
  
  /**
   * 
   * @return 
   */
  public HashMap<String,ScenarioElement> getWholeScenario(){
    return this.scenario;
  }
  
  /**
   * 
   * @param elementId
   * @param core 
   * @return  
   */
  public String addElement(String elementId, ArrayList<String> core){
    this.scenario.put(elementId, new ScenarioElement(elementId,core));
    return elementId;
  }
  
  /**
   * 
   * @param core
   * @return 
   */
  public String addElement(ArrayList<String> core){
    String newId = createID();
    this.scenario.put(newId, new ScenarioElement(newId,core));
    return newId;
  }
  
  /**
   * 
   * @param elementId 
   */
  public void removeElement(String elementId){
    // previous and next ?
    if(this.scenario.get(elementId).hasNext()){
      for(String next : this.scenario.get(elementId).getNextElements()){
        this.scenario.get(next).removePrevious(elementId);
      }
    }
    if(this.scenario.get(elementId).hasPrevious()){
      for(String previous : this.scenario.get(elementId).getPreviousElements()){
        this.scenario.get(previous).removeNext(elementId);
      }
    }
    this.scenario.remove(elementId);
  }
  
  /**
   * 
   * @return 
   */
  public String getTitle(){
    return this.title;
  }
  
  /**
   * 
   * @param title 
   */
  public void setTitle(String title){
    this.title = title;
  }
  
  
  /****************************************************************************/
  /** Tool Methods                                                           **/
  /****************************************************************************/
  
  /**
   * Increment a counter in order to provide a unique identification for a (new)
   *
   * @return A new unique identification string.
   */
  public static synchronized String createID()
  {
    return ("Element" + String.valueOf(idCounter++));
  } 
  
  /**
   * This function allows to check if an identification string is already in use
   * within the current scenario.
   * 
   * @param elementId the element id to check.
   * @return true if it exists in the element map, false otherwise.
   */
  public boolean existInScenario(String elementId){
    return this.scenario.containsKey(elementId);
  }
  
  
  /**
   * A string version of the current scenario. This is dedicated to testing.
   * 
   * @return A string version of the current sceanrio.
   */
  @Override
  public String toString(){
    String toReturn = this.title + "\r\n";
    for(String id : this.scenario.keySet()){
      toReturn += "ElementId: " + id + "\r\n";
      for(String core : this.scenario.get(id).getCore()){
        toReturn += " - " + core + "\r\n";
      }
      toReturn += "\r\n------\r\n";
    }
    return toReturn;
  }
  
}
