package ihm;

import graphstream.MyGraph;
import java.net.URL;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import org.graphstream.ui.view.Viewer;
import scenario.Scenario;
import tools.XmlTool;

/**
 * Main user interface class for creation and management of a Scenario for
 * tabletop rpg or various history.
 * 
 * @author Nicolas Brax
 */
public class RPGScenarioCreationIHM extends javax.swing.JFrame {

  /****************************************************************************/
  /** Private Attributes                                                     **/
  /****************************************************************************/
  
  /**
   * The current scenario to be created and displayed into the user interface.
   */
  private Scenario myScenario = new Scenario();
  
  /**
   * A variable to handle the several id to be displayed into the left list of
   * the user interface.
   */
  private DefaultListModel elementList = new DefaultListModel();
  
  /**
   * An attribute to indicate the scenario state, i.e. wether it is saved or not.
   */
  private boolean saveNeeded;
  
  /**
   * The object that contains the graph representing the current loaded or
   * created scenario.
   */
  private MyGraph scenarioGraph;
  
  /**
   * For easy code, store the id of the currently selected node if one is.
   */
  private String currentSelectedNode;
  
  private Viewer graphView;
    
  
  /****************************************************************************/
  /** Private Attributes                                                     **/
  /****************************************************************************/
  
  /**
   * Default Constructor
   * Creates new form RPGScenarioCreationIHM
   */
  public RPGScenarioCreationIHM() {
    initComponents();                                     // auto-generated
    
    this.setTitle("RPGScenario Management v.0.1.0");      // title of the frame and software
    URL iconURL = getClass().getResource("favicon.png");  // icon for the frame
    ImageIcon icon = new ImageIcon(iconURL);
    this.setIconImage(icon.getImage());
    
    XmlTool xml = new XmlTool();                          // retrieving all the available scenarii
    for(String s : xml.getAllScenarioTitles()){
      jcbbScenarioChoice.addItem(s);                      // to be put into a combo box
    }
    
    jlblScenarioTitle.setText("");
    
    // graph viewer initialisation
    scenarioGraph = new MyGraph();
    scenarioGraph.display();
    // todo: launch some listener of a kinf and thread and stuff... :/
    
    
    currentSelectedNode = "";
    
    // because it is not implemented yet.
    jcbbDifficulty.setEnabled(false);
    jtextNbElement.setEnabled(false);
    jbtnRandomGeneration.setEnabled(false);
    
    this.saveNeeded = false;                              // initial state, no save is needed obviously
  }
  
  /**
   * Give the current scenario related to the launched user interface.
   * 
   * @return the current scenario
   */
  public Scenario getScenario(){
    return this.myScenario;
  }
  
  /**
   * Save the current scenario into an xml file named after the title of the
   * scenario. 
   */
  public void saveScenario(){
    XmlTool xml = new XmlTool();
    xml.saveScenario(this.myScenario);
    this.setTitle(this.getTitle().substring(1));
    this.saveNeeded = false;
  }

  /****************************************************************************/
  /** The generated methods from NetBeans Swing Interface                    **/
  /****************************************************************************/
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jpanelGraphView = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jtxtElementId = new javax.swing.JTextField();
    jScrollPane1 = new javax.swing.JScrollPane();
    jtxtElementCore = new javax.swing.JTextArea();
    jScrollPane2 = new javax.swing.JScrollPane();
    jlistElement = new javax.swing.JList<>();
    jbtnAddElement = new javax.swing.JButton();
    jbtnRemoveElement = new javax.swing.JButton();
    jbtnRandomGeneration = new javax.swing.JButton();
    jLabel3 = new javax.swing.JLabel();
    jtextNbElement = new javax.swing.JTextField();
    jLabel4 = new javax.swing.JLabel();
    jcbbDifficulty = new javax.swing.JComboBox<>();
    jcbbScenarioChoice = new javax.swing.JComboBox<>();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jtextScenarioTitle = new javax.swing.JTextField();
    jbtnLoadScenario = new javax.swing.JButton();
    jButton1 = new javax.swing.JButton();
    jbtnQuit = new javax.swing.JButton();
    jlblScenarioTitle = new javax.swing.JLabel();
    jButton3 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setMinimumSize(new java.awt.Dimension(1024, 677));
    setResizable(false);

    jpanelGraphView.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

    javax.swing.GroupLayout jpanelGraphViewLayout = new javax.swing.GroupLayout(jpanelGraphView);
    jpanelGraphView.setLayout(jpanelGraphViewLayout);
    jpanelGraphViewLayout.setHorizontalGroup(
      jpanelGraphViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 482, Short.MAX_VALUE)
    );
    jpanelGraphViewLayout.setVerticalGroup(
      jpanelGraphViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 0, Short.MAX_VALUE)
    );

    jLabel1.setText("Element Id: ");

    jLabel2.setText("Element Core: ");

    jtxtElementCore.setColumns(20);
    jtxtElementCore.setRows(5);
    jScrollPane1.setViewportView(jtxtElementCore);

    jlistElement.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jlistElementMouseClicked(evt);
      }
    });
    jScrollPane2.setViewportView(jlistElement);

    jbtnAddElement.setText("Add Element");
    jbtnAddElement.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jbtnAddElementActionPerformed(evt);
      }
    });

    jbtnRemoveElement.setText("Remove Element");
    jbtnRemoveElement.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jbtnRemoveElementActionPerformed(evt);
      }
    });

    jbtnRandomGeneration.setText("Random Generation");

    jLabel3.setText("Number of Element:");

    jLabel4.setText("Difficulty:");

    jcbbDifficulty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Piece of Cake", "Easy", "Normal", "Hard", "Hell on Earth" }));

    jLabel5.setText("Choose a Scenario or make a new one.");

    jLabel6.setText("Scenario Title: ");

    jbtnLoadScenario.setText("Load Scenario");
    jbtnLoadScenario.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jbtnLoadScenarioActionPerformed(evt);
      }
    });

    jButton1.setText("Save Scenario");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    jbtnQuit.setText("Quit");
    jbtnQuit.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jbtnQuitActionPerformed(evt);
      }
    });

    jlblScenarioTitle.setText("jLabel7");

    jButton3.setText("Clean Fields");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel1)
                  .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jtxtElementId, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jtextScenarioTitle)))
              .addComponent(jLabel2)
              .addComponent(jLabel5)
              .addComponent(jcbbScenarioChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jbtnLoadScenario, javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                  .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(jbtnAddElement, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(jbtnRemoveElement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
              .addComponent(jbtnRandomGeneration, javax.swing.GroupLayout.Alignment.TRAILING)
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                  .addComponent(jLabel3)
                  .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addComponent(jcbbDifficulty, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(jtextNbElement)))))
          .addGroup(layout.createSequentialGroup()
            .addGap(24, 24, 24)
            .addComponent(jbtnQuit)))
        .addGap(21, 21, 21)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jlblScenarioTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jpanelGraphView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
        .addGap(18, 18, 18))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
          .addGroup(layout.createSequentialGroup()
            .addGap(17, 17, 17)
            .addComponent(jLabel5)
            .addGap(18, 18, 18)
            .addComponent(jcbbScenarioChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jbtnLoadScenario)
            .addGap(71, 71, 71)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel6)
              .addComponent(jtextScenarioTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel1)
              .addComponent(jtxtElementId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jbtnAddElement, javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(jbtnRemoveElement))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jButton1)
              .addComponent(jButton3))
            .addGap(63, 63, 63)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel3)
              .addComponent(jtextNbElement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel4)
              .addComponent(jcbbDifficulty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jbtnRandomGeneration)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
            .addComponent(jbtnQuit)
            .addGap(8, 8, 8))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jlblScenarioTitle)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jpanelGraphView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jbtnAddElementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddElementActionPerformed
    // set the title if it has not be done yet
    if(this.myScenario.getTitle().isEmpty()){
      this.myScenario.setTitle(jtextScenarioTitle.getText());
    }
    
    // add the several components of the element
    ArrayList<String> tmpCore = new ArrayList<>();
    Document doc = jtxtElementCore.getDocument();
    try{
      String tmp = doc.getText(0,doc.getLength());
      String[] parts = tmp.split("\n");
      for(int i = 0 ; i < parts.length ; ++i){
        tmpCore.add(parts[i]);
      }
    }
    catch(BadLocationException e){
      e.printStackTrace();
    }
    
    // create the scenario element and add it to the current scenario
    String id;
    if(jtxtElementId.getText().isEmpty()){
      id = this.myScenario.addElement(tmpCore);
    }
    else{
      id = this.myScenario.addElement(jtxtElementId.getText(),tmpCore);
    }
    
    // add the id to the list of element and display it
    if(!elementList.contains(id)){
      elementList.addElement(id);
      jlistElement.setModel(elementList);
    }
    
    // set the title on the interface if it has not been made before
    if(jlblScenarioTitle.getText().equalsIgnoreCase("")){
      jlblScenarioTitle.setText(this.myScenario.getTitle());  
    }
    
    // add the node on the graph visualisation
    scenarioGraph.addNode(id);
    
    // erase all but the title for the next element to be inputed
    jtxtElementId.setText("");
    try{
      doc.remove(0, doc.getLength());
    }
    catch(BadLocationException e){
      e.printStackTrace();
    }
    
    // indicate that a scenario save is needed
    this.saveNeeded = true;
    if(!this.getTitle().contains("*")){
      this.setTitle("*" + this.getTitle());
    }
  }//GEN-LAST:event_jbtnAddElementActionPerformed

  private void jbtnRemoveElementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRemoveElementActionPerformed
    this.myScenario.removeElement(jtxtElementId.getText()); // remove the element from the scenario
    elementList.removeElement(jtxtElementId.getText());     // remove the id from the list
    scenarioGraph.removeNode(jtxtElementId.getText());      // remove the node from the graph visualisation
  }//GEN-LAST:event_jbtnRemoveElementActionPerformed

  private void jlistElementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlistElementMouseClicked
    if(evt.getClickCount() == 2){
      String selected = jlistElement.getSelectedValue();
      jtxtElementId.setText(this.myScenario.getElement(selected).getElementId());
      jtxtElementCore.setText(this.myScenario.getElement(selected).getCore().get(0));
      
      Document doc = jtxtElementCore.getDocument();
      try{
        doc.remove(0, doc.getLength());
      }
      catch(BadLocationException e){
        e.printStackTrace();
      }
      for(String s : this.myScenario.getElement(selected).getCore()){
        try{
          doc.insertString(doc.getLength(),s,null);
          doc.insertString(doc.getLength(),"\r\n",null);
        }
        catch(BadLocationException e){
          e.printStackTrace();
        }
      }
      
      // color or border of the node and links
      if(!currentSelectedNode.isEmpty()){
        scenarioGraph.updateNode(currentSelectedNode,false);
        //TODO: unselect all its linked edge
      }
      currentSelectedNode = this.myScenario.getElement(selected).getElementId();
      scenarioGraph.updateNode(currentSelectedNode, true);
      
      if(this.myScenario.getElement(selected).hasNext()){
        for(String next : myScenario.getElement(selected).getNextElements()){
          scenarioGraph.updateLink(selected+next,true);
        }//for next
      }//if hasNext
      
      if(this.myScenario.getElement(selected).hasPrevious()){
        for(String previous : myScenario.getElement(selected).getPreviousElements()){
          scenarioGraph.updateLink(previous+selected,true);
        }//for previous
      }//if hasPrevious
      
      //scenarioGraph.updateLink(id+next,true);
      
      // fill the left part to allow remove and edition
      
    }//if clickCount == 2
  }//GEN-LAST:event_jlistElementMouseClicked

  private void jbtnLoadScenarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLoadScenarioActionPerformed
    XmlTool xml = new XmlTool();
    this.myScenario = xml.loadScenario((String)jcbbScenarioChoice.getSelectedItem()); // load the scenario set in the combo box
    jtxtElementId.setText("");                                                        // no display to do beforehand
    jtxtElementCore.setText("");
    jtextScenarioTitle.setText("");
    elementList.clear();
    jlblScenarioTitle.setText(this.myScenario.getTitle());                            // indicate the scenario name/title
    for(String id : this.myScenario.getWholeScenario().keySet()){                     // for each element in the scenario
      elementList.addElement(id);                                                     // add the id to the list
      scenarioGraph.addNode(id);
      if(this.myScenario.getElement(id).hasNext()){
        for(String next : myScenario.getElement(id).getNextElements()){
          scenarioGraph.addLink(id,next);
        }// for next
      }// if hasNext()
    }
    scenarioGraph.addPipe();
    jlistElement.setModel(elementList);
  }//GEN-LAST:event_jbtnLoadScenarioActionPerformed

  private void jbtnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnQuitActionPerformed
    if(this.saveNeeded){
      int dialogButton = JOptionPane.YES_NO_OPTION;
      int dialogResult = JOptionPane.showConfirmDialog (null, "Would you like to save before quit?","Warning",dialogButton);
      if(dialogResult == JOptionPane.YES_OPTION){
        saveScenario();
      }
    }
    System.exit(0);  
  }//GEN-LAST:event_jbtnQuitActionPerformed

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    saveScenario();
  }//GEN-LAST:event_jButton1ActionPerformed

  /**
   * Launching the thread containing the user interface
   * (auto-generated)
   * 
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(RPGScenarioCreationIHM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(RPGScenarioCreationIHM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(RPGScenarioCreationIHM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(RPGScenarioCreationIHM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new RPGScenarioCreationIHM().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton3;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JButton jbtnAddElement;
  private javax.swing.JButton jbtnLoadScenario;
  private javax.swing.JButton jbtnQuit;
  private javax.swing.JButton jbtnRandomGeneration;
  private javax.swing.JButton jbtnRemoveElement;
  private javax.swing.JComboBox<String> jcbbDifficulty;
  private javax.swing.JComboBox<String> jcbbScenarioChoice;
  private javax.swing.JLabel jlblScenarioTitle;
  private javax.swing.JList<String> jlistElement;
  private javax.swing.JPanel jpanelGraphView;
  private javax.swing.JTextField jtextNbElement;
  private javax.swing.JTextField jtextScenarioTitle;
  private javax.swing.JTextArea jtxtElementCore;
  private javax.swing.JTextField jtxtElementId;
  // End of variables declaration//GEN-END:variables
}


/*

Document doc = IntelS.getDocument();
      try{
        doc.remove(0, doc.getLength());
      }
      catch(BadLocationException e){
        e.printStackTrace();
      }
      for(String s : supervisors.get(selectedItem).getNotes()){
        try{
          doc.insertString(doc.getLength(),s,null);
          doc.insertString(doc.getLength(),"\r\n",null);
        }
        catch(BadLocationException e){
          e.printStackTrace();
        }



    /*
    graph.addNode("A" );
graph.addNode("B" );
graph.addNode("C" );
graph.addEdge("AB", "A", "B");
graph.addEdge("BC", "B", "C");
graph.addEdge("CA", "C", "A");

//graph.display();
    

*/